### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by parsboy66** [WGLab/LongGF#11]
Thanks for great job, 

I have faced with some issues while installing package:
through Conda after installation, by running LongGF according to the instructions I received this error:
 version `GLIBCXX_3.4.21' not found (required by LongGF)

also based on the GitHub installation this error:
/bin/ld: warning: libcrypto.so.1.0.0, needed by ./lib/libhts.so, not found (try using -rpath or -rpath-link)

do you think does it need other libraries ?  or its cos  of I installed it in under Conda environment ?

Thanks in advance

**Comment by parsboy66** [comment]
ok thanks, it solved by addressing the lib folder in the bin.

**Comment by liuqianhn** [comment]
@parsboy66 Thanks for your comments and it is great that you solved it by yourself. I closed this issue since you have solved the issue.

**Comment by loganylchen** [comment]
Hi @liuqianhn,

I am facing some problems with installing the tool through the source code. I followed the instruction, but encountered 
```
/usr/bin/ld: /tmp/ccthd9EE.o: in function `get_multiple_mapped_reads[abi:cxx11](char const*, long, int, int)':
/opt/LongGF-0.1.2/bin/get_gfFrombam.c:209: undefined reference to `bam_init1'
/usr/bin/ld: /opt/LongGF-0.1.2/bin/get_gfFrombam.c:212: undefined reference to `hts_open'
/usr/bin/ld: /opt/LongGF-0.1.2/bin/get_gfFrombam.c:218: undefined reference to `sam_hdr_read'
/usr/bin/ld: /opt/LongGF-0.1.2/bin/get_gfFrombam.c:230: undefined reference to `sam_read1'
/usr/bin/ld: /opt/LongGF-0.1.2/bin/get_gfFrombam.c:396: undefined reference to `bam_destroy1'
/usr/bin/ld: /tmp/ccthd9EE.o: in function `get_multiple_mapped_reads[abi:cxx11](char const*, long, int, int)':
/root/anaconda3/envs/test/include/htslib/sam.h:393: undefined reference to `sam_hdr_destroy'
/usr/bin/ld: /tmp/ccthd9EE.o: in function `get_multiple_mapped_reads[abi:cxx11](char const*, long, int, int)':
/opt/LongGF-0.1.2/bin/get_gfFrombam.c:398: undefined reference to `hts_close'
/usr/bin/ld: /tmp/ccthd9EE.o: in function `m_check_gene_fusion(char const*, char const*, int, long, int, long, int, int, int)':
/opt/LongGF-0.1.2/bin/get_gfFrombam.c:512: undefined reference to `bam_init1'
/usr/bin/ld: /opt/LongGF-0.1.2/bin/get_gfFrombam.c:515: undefined reference to `hts_open'
/usr/bin/ld: /opt/LongGF-0.1.2/bin/get_gfFrombam.c:521: undefined reference to `sam_hdr_read'
/usr/bin/ld: /opt/LongGF-0.1.2/bin/get_gfFrombam.c:541: undefined reference to `sam_read1'
/usr/bin/ld: /opt/LongGF-0.1.2/bin/get_gfFrombam.c:1058: undefined reference to `bam_destroy1'
/usr/bin/ld: /tmp/ccthd9EE.o: in function `m_check_gene_fusion(char const*, char const*, int, long, int, long, int, int, int)':
/root/anaconda3/envs/test/include/htslib/sam.h:393: undefined reference to `sam_hdr_destroy'
/usr/bin/ld: /tmp/ccthd9EE.o: in function `m_check_gene_fusion(char const*, char const*, int, long, int, long, int, int, int)':
/opt/LongGF-0.1.2/bin/get_gfFrombam.c:1060: undefined reference to `hts_close'
collect2: error: ld returned 1 exit status
```

May I ask your help for fixing it?

Thanks in advance

**Comment by liuqianhn** [comment]
@loganylchen It seems errors to link to HTSlib. Please make sure that you have /opt/LongGF-0.1.2/bin/include and /opt/LongGF-0.1.2/bin/lib when you compile under /opt/LongGF-0.1.2/bin/ folder. It the issues cannot be solved, please try to install htslib by yourself (a better way to install htslib is to use `conda install -c bioconda htslib` if possible), and set the paths below:

```
export C_INCLUDE_PATH="/full/path/to/your/file/include/":$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH="/full/path/to/your/file/include/":$CPLUS_INCLUDE_PATH
```

and

```
export LD_LIBRARY_PATH="/full/path/to/your/file/lib/":$LD_LIBRARY_PATH
```

`/full/path/to/your/file/` is where you installed HTSlib.

**Comment by loganylchen** [comment]
Thanks, @liuqianhn, for the quick reply.
However, even after trying what you replied to, I am still not able to install it. 
```
echo $LD_LIBRARY_PATH $C_INCLUDE_PATH $CPLUS_INCLUDE_PATH
/opt/conda/envs/longgf /opt/conda/envs/longgf/include /opt/conda/envs/longgf/include
```
`ls /opt/conda/envs/longgf/include`
![image](https://user-images.githubusercontent.com/25150929/197707872-e961ea1e-2a01-4444-a350-50c026cad053.png)

`ls /opt/conda/envs/longgf/lib`
![image](https://user-images.githubusercontent.com/25150929/197708022-c7039a1a-51bf-4fc8-afd3-bc16ed60e253.png)

Then I tried `g++ -g -Wall -O3 -std=c++11 -I$PREFIX/include -L$PREFIX/lib -lhts -o LongGF _com_fun_.c _gtf_struct_.c get_gfFrombam.c`, in which ,`$PREFIX` is `/opt/conda/envs/longgf/`

**Comment by liuqianhn** [comment]
@loganylchen I cannot reproduce the error. But
1. LD_LIBRARY_PATH should include /opt/conda/envs/longgf/lib rather than /opt/conda/envs/longgf. Meanwhile, I did not see libhts* in the lib folder you shared. Maybe you do not share all of them(if this is not the case, please add -L ./lib/ in the compile command when you are in the LongGF/bin folder for compile)
2. If you have used 'conda install -c bioconda longgf ' for installation, you already have an older version of LongGF under /opt/conda/envs/longgf/bin. You can also use this older version.

**Comment by loganylchen** [comment]
@liuqianhn, I may make a mistake in the previous reply. I set  `LD_LIBRARY_PATH=/opt/conda/envs/longgf/lib` indeed. Now I am trying to install the LongGF on a very clean system (pure ubuntu image through docker), but still can't make it. I include the dockerfile below, hope which could make the processes clearly. 

```Dockerfile
FROM ubuntu:22.04



ENV DEBIAN_FRONTEND=noninteractive
ENV C_INCLUDE_PATH=/opt/softwares/htslib/include
ENV CPLUS_INCLUDE_PATH=/opt/softwares/htslib/include
ENV LD_LIBRARY_PATH=/opt/softwares/htslib/lib
ENV PREFIX=/opt/softwares/htslib

ENV PATH=/usr/bin:/bin:/usr/local/bin:/opt/bin:$PATH


ENV build_deps="build-essential \
        zlib1g-dev \
        libbz2-dev \
        liblzma-dev \
        libdeflate-tools \
        cmake\
        zip\
        git \
        libcurl4-openssl-dev\
        libssl-dev \
        wget "

RUN apt update && \
    apt install -y $build_deps 

RUN mkdir -p /opt/bin
RUN cd /tmp/ && \
    wget https://github.com/ebiggers/libdeflate/archive/refs/tags/v1.14.tar.gz && \
    tar -zxvf v1.14.tar.gz && \
    cd libdeflate-1.14 && make &&  make install && \
	cd /tmp/ && \
    wget https://github.com/samtools/htslib/releases/download/1.12/htslib-1.12.tar.bz2 && \
    tar -jxvf htslib-1.12.tar.bz2 && \
    cd htslib-1.12 && \
    ./configure --prefix=/opt/softwares/htslib && make && make install 

RUN cd /tmp && \
    wget https://github.com/WGLab/LongGF/archive/refs/tags/v0.1.2.tar.gz && \
    tar -vxzf v0.1.2.tar.gz && \
    cd LongGF-0.1.2/bin && \
    g++ -g -Wall -O3 -std=c++11 -I$PREFIX/include -L$PREFIX/lib -lhts -o LongGF _com_fun_.c _gtf_struct_.c get_gfFrombam.c 

```

After building the image, I got almost the same errors:
![image](https://user-images.githubusercontent.com/25150929/197922546-30e15411-6943-4aa6-ba7a-3157d51b8190.png)

**Comment by loganylchen** [comment]
Hi @liuqianhn , is there any updates on this issue?

**Comment by liuqianhn** [comment]
Apologies for the late reply since I was just back from a conference this weekend.
Try to add ` $PREFIX/lib/libhts.so` to the last command.

**Comment by loganylchen** [comment]
@liuqianhn Thanks, it works now. I will try the LongGF on my datasets.
